import { library } from "@fortawesome/fontawesome-svg-core";
import { fab } from "@fortawesome/free-brands-svg-icons";
import {
  faHouse,
  faVideo,
  faUserGroup,
  faUser,
  faFloppyDisk,
  faMessage,
  faPlus,
  faBell,
  faGear,
  faMagnifyingGlass,
  faClose,
  faArrowLeft,
  faBars,
  faPalette,
  faEyeSlash,
  faEye,
  faCheck,
  faDotCircle,
  faCircleCheck,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  fab,
  faHouse,
  faVideo,
  faUserGroup,
  faUser,
  faFloppyDisk,
  faMessage,
  faPlus,
  faBell,
  faGear,
  faMagnifyingGlass,
  faClose,
  faArrowLeft,
  faBars,
  faPalette,
  faEyeSlash,
  faEye,
  faCheck,
  faDotCircle,
  faCircleCheck
);
